// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict";

var Curry = require("bs-platform/lib/js/curry.js");
var DemoGen = require("./Demo.gen");

var dirname = DemoGen.dirname;

var root = Curry._1(dirname, "/User/github");

var parse = DemoGen.parse;

exports.dirname = dirname;
exports.root = root;
exports.parse = parse;
/* dirname Not a pure module */
