// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

var root = Curry._1(dirname, "/User/github");

exports.root = root;
/* root Not a pure module */
